import type {
  Category,
  Course,
  EnrolledCourse,
  Instructor,
  Purchase,
} from "@/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Web Development",
    slug: "web-development",
    icon: "Code",
    courseCount: 234,
  },
  {
    id: "2",
    name: "Mobile Development",
    slug: "mobile-development",
    icon: "Smartphone",
    courseCount: 128,
  },
  {
    id: "3",
    name: "Data Science",
    slug: "data-science",
    icon: "BarChart3",
    courseCount: 189,
  },
  {
    id: "4",
    name: "Cloud Computing",
    slug: "cloud-computing",
    icon: "Cloud",
    courseCount: 96,
  },
  {
    id: "5",
    name: "Cyber Security",
    slug: "cyber-security",
    icon: "Shield",
    courseCount: 74,
  },
  {
    id: "6",
    name: "AI & Machine Learning",
    slug: "ai-machine-learning",
    icon: "Brain",
    courseCount: 156,
  },
  {
    id: "7",
    name: "DevOps",
    slug: "devops",
    icon: "GitBranch",
    courseCount: 67,
  },
  {
    id: "8",
    name: "UI/UX Design",
    slug: "ui-ux-design",
    icon: "Palette",
    courseCount: 112,
  },
];

export const instructors: Instructor[] = [
  {
    id: "1",
    name: "Dr. Angela Yu",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    title: "Lead Instructor & Developer",
    bio: "I'm Angela, a developer with a passion for teaching. I'm the lead instructor at the London App Brewery. I've helped hundreds of thousands of students learn to code.",
    rating: 4.7,
    studentCount: 2500000,
    courseCount: 12,
  },
  {
    id: "2",
    name: "Maximilian Schwarzmüller",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    title: "Professional Web Developer & Instructor",
    bio: "Experience as a web developer since 2012. Teaching since 2015. I love creating detailed guides that help you master web development.",
    rating: 4.6,
    studentCount: 1800000,
    courseCount: 34,
  },
  {
    id: "3",
    name: "Stephen Grider",
    avatar: "https://randomuser.me/api/portraits/men/46.jpg",
    title: "Engineering Architect",
    bio: "Stephen Grider has been building complex Javascript front ends for top corporations. He has experience working with enterprise-level companies.",
    rating: 4.6,
    studentCount: 1200000,
    courseCount: 28,
  },
  {
    id: "4",
    name: "Jonas Schmedtmann",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    title: "Web Developer, Designer, and Teacher",
    bio: "Hi, I'm Jonas! I'm one of Udemy's top instructors. I'm a full-stack web developer and designer with a passion for building beautiful things from scratch.",
    rating: 4.8,
    studentCount: 1800000,
    courseCount: 7,
  },
  {
    id: "5",
    name: "Colt Steele",
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    title: "Developer and Bootcamp Instructor",
    bio: "Colt is a developer with a serious love for teaching. He has spent the last few years teaching people to program at 2 different immersive bootcamps.",
    rating: 4.7,
    studentCount: 1500000,
    courseCount: 15,
  },
  {
    id: "6",
    name: "Brad Traversy",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    title: "Full Stack Web Developer & Instructor",
    bio: "I have been a full stack developer for around 12 years now and have created many successful courses on Udemy and YouTube.",
    rating: 4.7,
    studentCount: 900000,
    courseCount: 22,
  },
];

const makeSections = (count: number) =>
  Array.from({ length: count }, (_, i) => ({
    id: `section-${i + 1}`,
    title: `Section ${i + 1}: ${["Getting Started", "Core Concepts", "Advanced Patterns", "Real-World Projects", "Testing & Deployment", "Performance Optimization"][i % 6]}`,
    lessons: Array.from(
      { length: Math.floor(Math.random() * 6) + 4 },
      (_, j) => ({
        id: `lesson-${i}-${j}`,
        title: `Lesson ${j + 1}`,
        duration: `${Math.floor(Math.random() * 20) + 5}:${String(Math.floor(Math.random() * 60)).padStart(2, "0")}`,
        isPreview: i === 0 && j < 2,
      }),
    ),
  }));

const makeReviews = () => [
  {
    id: "r1",
    userName: "Alex Thompson",
    userAvatar: "https://randomuser.me/api/portraits/men/1.jpg",
    rating: 5,
    comment:
      "Excellent course! The instructor explains everything clearly and the projects are very practical.",
    date: "2025-12-15",
  },
  {
    id: "r2",
    userName: "Maria Garcia",
    userAvatar: "https://randomuser.me/api/portraits/women/2.jpg",
    rating: 4,
    comment:
      "Very good course, learned a lot. Some sections could use a bit more depth but overall great.",
    date: "2025-11-20",
  },
  {
    id: "r3",
    userName: "James Wilson",
    userAvatar: "https://randomuser.me/api/portraits/men/3.jpg",
    rating: 5,
    comment:
      "One of the best courses I have taken. Highly recommend for anyone looking to level up.",
    date: "2025-10-08",
  },
  {
    id: "r4",
    userName: "Sarah Chen",
    userAvatar: "https://randomuser.me/api/portraits/women/4.jpg",
    rating: 4,
    comment:
      "Great content and well structured. The code-along format makes it easy to follow.",
    date: "2025-09-14",
  },
];

export const courses: Course[] = [
  {
    id: "1",
    slug: "complete-react-developer",
    title: "The Complete React Developer Course",
    subtitle: "Learn React, Hooks, Redux, React Router, Next.js, and more!",
    thumbnail:
      "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&h=340&fit=crop",
    instructor: instructors[0]!,
    category: categories[0]!,
    price: 12.99,
    originalPrice: 84.99,
    rating: 4.7,
    reviewCount: 42300,
    studentCount: 185000,
    level: "All Levels",
    language: "English",
    duration: "40 hours",
    lessonCount: 320,
    description:
      "This course will take you from zero to hero in React development. You will learn everything from the fundamentals to advanced patterns used in production applications.",
    whatYouLearn: [
      "Build powerful, fast, user-friendly and reactive web apps",
      "Apply for high-paid jobs or work as a freelancer",
      "Learn React Hooks, Redux, React Router, Next.js",
      "Learn all about React Hooks and React Components",
    ],
    requirements: [
      "JavaScript + HTML + CSS fundamentals",
      "No prior React knowledge required",
    ],
    sections: makeSections(12),
    reviews: makeReviews(),
    updatedAt: "2025-12-01",
    isBestseller: true,
  },
  {
    id: "2",
    slug: "nodejs-complete-guide",
    title: "NodeJS - The Complete Guide (MVC, REST APIs, GraphQL, Deno)",
    subtitle: "Master Node.js by building practical, real-world applications",
    thumbnail:
      "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=600&h=340&fit=crop",
    instructor: instructors[1]!,
    category: categories[0]!,
    price: 14.99,
    originalPrice: 89.99,
    rating: 4.6,
    reviewCount: 38200,
    studentCount: 210000,
    level: "All Levels",
    language: "English",
    duration: "36 hours",
    lessonCount: 290,
    description:
      "Join the most comprehensive Node.js course and learn to build REST APIs, GraphQL APIs, add authentication, use MongoDB, SQL and much more!",
    whatYouLearn: [
      "Build backend server-side applications with NodeJS",
      "Build REST APIs and GraphQL APIs",
      "Master authentication and authorization",
      "Use databases like MongoDB and SQL",
    ],
    requirements: [
      "General knowledge of how the web works",
      "Basic JavaScript knowledge",
    ],
    sections: makeSections(14),
    reviews: makeReviews(),
    updatedAt: "2025-11-15",
    isBestseller: true,
  },
  {
    id: "3",
    slug: "python-data-science-ml",
    title: "Python for Data Science and Machine Learning Bootcamp",
    subtitle:
      "Learn how to use NumPy, Pandas, Seaborn, Matplotlib, Scikit-Learn, and more!",
    thumbnail:
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&h=340&fit=crop",
    instructor: instructors[2]!,
    category: categories[2]!,
    price: 11.99,
    originalPrice: 94.99,
    rating: 4.5,
    reviewCount: 51200,
    studentCount: 450000,
    level: "Intermediate",
    language: "English",
    duration: "25 hours",
    lessonCount: 165,
    description:
      "Are you ready to start your path to becoming a Data Scientist? This comprehensive course will be your guide.",
    whatYouLearn: [
      "Use Python for Data Science and Machine Learning",
      "Implement Machine Learning Algorithms",
      "Use NumPy, Pandas for data analysis",
      "Create data visualizations with Matplotlib and Seaborn",
    ],
    requirements: ["Basic Python knowledge", "Understanding of basic math"],
    sections: makeSections(10),
    reviews: makeReviews(),
    updatedAt: "2025-10-20",
  },
  {
    id: "4",
    slug: "flutter-complete-guide",
    title: "Flutter & Dart - The Complete Guide",
    subtitle: "Build iOS and Android apps with a single codebase",
    thumbnail:
      "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=600&h=340&fit=crop",
    instructor: instructors[1]!,
    category: categories[1]!,
    price: 13.99,
    originalPrice: 79.99,
    rating: 4.6,
    reviewCount: 29800,
    studentCount: 165000,
    level: "Beginner",
    language: "English",
    duration: "42 hours",
    lessonCount: 380,
    description:
      "A complete guide to the Flutter SDK and Dart for building native iOS and Android apps.",
    whatYouLearn: [
      "Build engaging native mobile apps for iOS and Android",
      "Use features like Google Maps, Camera, Authentication",
      "Learn Dart and Flutter from the ground up",
      "Build production-ready apps",
    ],
    requirements: [
      "Basic programming knowledge helps",
      "No Flutter or Dart experience required",
    ],
    sections: makeSections(16),
    reviews: makeReviews(),
    updatedAt: "2025-09-28",
    isNew: true,
  },
  {
    id: "5",
    slug: "aws-certified-solutions-architect",
    title: "AWS Certified Solutions Architect - Associate",
    subtitle: "Pass the AWS Certified Solutions Architect Associate exam",
    thumbnail:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=340&fit=crop",
    instructor: instructors[4]!,
    category: categories[3]!,
    price: 15.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviewCount: 45600,
    studentCount: 320000,
    level: "Intermediate",
    language: "English",
    duration: "28 hours",
    lessonCount: 220,
    description:
      "Full practice exam included! Pass the AWS Certified Solutions Architect Associate certification.",
    whatYouLearn: [
      "Pass the AWS Certified Solutions Architect exam",
      "All 700+ slides available as downloadable PDF",
      "Understand the AWS fundamentals",
      "Master the core AWS services",
    ],
    requirements: [
      "No AWS Cloud experience is necessary",
      "A computer with an internet connection",
    ],
    sections: makeSections(18),
    reviews: makeReviews(),
    updatedAt: "2025-12-10",
    isBestseller: true,
  },
  {
    id: "6",
    slug: "ethical-hacking-complete",
    title: "The Complete Ethical Hacking Bootcamp",
    subtitle:
      "Learn network security, penetration testing, and ethical hacking",
    thumbnail:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=340&fit=crop",
    instructor: instructors[4]!,
    category: categories[4]!,
    price: 16.99,
    originalPrice: 109.99,
    rating: 4.5,
    reviewCount: 18900,
    studentCount: 98000,
    level: "Beginner",
    language: "English",
    duration: "24 hours",
    lessonCount: 180,
    description:
      "Become an ethical hacker that can hack computer systems like black hat hackers and secure them like security experts.",
    whatYouLearn: [
      "Learn ethical hacking concepts and techniques",
      "Master penetration testing",
      "Understand network security",
      "Write Python scripts for hacking",
    ],
    requirements: ["Basic IT knowledge", "No programming experience required"],
    sections: makeSections(8),
    reviews: makeReviews(),
    updatedAt: "2025-11-01",
    isNew: true,
  },
  {
    id: "7",
    slug: "javascript-complete-course",
    title: "The Complete JavaScript Course: From Zero to Expert!",
    subtitle: "Master JavaScript with projects, challenges, and theory",
    thumbnail:
      "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=600&h=340&fit=crop",
    instructor: instructors[3]!,
    category: categories[0]!,
    price: 12.99,
    originalPrice: 84.99,
    rating: 4.8,
    reviewCount: 67800,
    studentCount: 580000,
    level: "Beginner",
    language: "English",
    duration: "69 hours",
    lessonCount: 430,
    description:
      "The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory. Many courses in one!",
    whatYouLearn: [
      "Become an advanced, confident, and modern JavaScript developer",
      "Build 6 beautiful real-world projects",
      "JavaScript fundamentals: variables, if/else, operators, boolean logic",
      "Modern OOP: Classes, constructor, prototypal inheritance",
    ],
    requirements: ["No coding experience necessary", "A computer and internet"],
    sections: makeSections(20),
    reviews: makeReviews(),
    updatedAt: "2025-12-20",
    isBestseller: true,
  },
  {
    id: "8",
    slug: "deep-learning-tensorflow",
    title: "Complete TensorFlow 2.0 & Deep Learning Bootcamp",
    subtitle: "Neural networks, CNNs, RNNs, GANs, reinforcement learning",
    thumbnail:
      "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=340&fit=crop",
    instructor: instructors[2]!,
    category: categories[5]!,
    price: 18.99,
    originalPrice: 119.99,
    rating: 4.4,
    reviewCount: 12300,
    studentCount: 67000,
    level: "Advanced",
    language: "English",
    duration: "32 hours",
    lessonCount: 245,
    description:
      "Learn TensorFlow 2.0 from scratch! Build neural networks and deep learning models.",
    whatYouLearn: [
      "Build TensorFlow models",
      "Understand deep learning concepts",
      "Create CNNs, RNNs, GANs",
      "Deploy models to production",
    ],
    requirements: [
      "Python programming knowledge",
      "Basic math knowledge (linear algebra)",
    ],
    sections: makeSections(12),
    reviews: makeReviews(),
    updatedAt: "2025-08-15",
  },
  {
    id: "9",
    slug: "docker-kubernetes-complete",
    title: "Docker & Kubernetes: The Practical Guide",
    subtitle:
      "Learn Docker, Docker Compose, Multi-Container Projects, and Kubernetes",
    thumbnail:
      "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&h=340&fit=crop",
    instructor: instructors[1]!,
    category: categories[6]!,
    price: 14.99,
    originalPrice: 89.99,
    rating: 4.7,
    reviewCount: 22100,
    studentCount: 142000,
    level: "Intermediate",
    language: "English",
    duration: "23 hours",
    lessonCount: 195,
    description:
      "Learn Docker, Docker Compose, Multi-Container Projects, Deployment and all about Kubernetes from the ground up!",
    whatYouLearn: [
      "Learn what Docker and Kubernetes are and why you might want to use them",
      "Learn how to install and use Docker on any OS",
      "Build your own custom images and containers",
      "Learn Kubernetes from the ground up",
    ],
    requirements: [
      "NO prior Docker or Kubernetes knowledge is required",
      "Basic web development knowledge",
    ],
    sections: makeSections(10),
    reviews: makeReviews(),
    updatedAt: "2025-11-25",
  },
  {
    id: "10",
    slug: "figma-ui-ux-design",
    title: "Complete Figma Masterclass: UI/UX Design from Scratch",
    subtitle: "Learn UI/UX design, prototyping, and design systems with Figma",
    thumbnail:
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=340&fit=crop",
    instructor: instructors[5]!,
    category: categories[7]!,
    price: 11.99,
    originalPrice: 74.99,
    rating: 4.6,
    reviewCount: 15400,
    studentCount: 89000,
    level: "Beginner",
    language: "English",
    duration: "18 hours",
    lessonCount: 140,
    description:
      "Master Figma and learn UI/UX design from scratch. Build real projects and create stunning designs.",
    whatYouLearn: [
      "Master Figma from beginner to advanced",
      "Create stunning UI designs",
      "Build interactive prototypes",
      "Create and manage design systems",
    ],
    requirements: [
      "No design experience required",
      "A computer (Figma works in the browser)",
    ],
    sections: makeSections(8),
    reviews: makeReviews(),
    updatedAt: "2025-10-05",
    isNew: true,
  },
  {
    id: "11",
    slug: "typescript-masterclass",
    title: "Understanding TypeScript - The Complete Developer's Guide",
    subtitle: "Learn TypeScript deeply and apply it to real projects",
    thumbnail:
      "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=600&h=340&fit=crop",
    instructor: instructors[1]!,
    category: categories[0]!,
    price: 13.99,
    originalPrice: 79.99,
    rating: 4.7,
    reviewCount: 28600,
    studentCount: 195000,
    level: "Intermediate",
    language: "English",
    duration: "15 hours",
    lessonCount: 125,
    description:
      "Don't limit the power of TypeScript to Angular - learn the basics, its features, workflows and how to use it!",
    whatYouLearn: [
      "Use TypeScript and its features like Types, ES6 Support, Classes, Modules, Interfaces",
      "Understand what TypeScript really is and how it works",
      "Why TypeScript offers a real advantage over vanilla JavaScript",
      "Learn TypeScript both in theory and applied to real projects",
    ],
    requirements: [
      "Basic JavaScript knowledge",
      "ES6 knowledge is a plus but not required",
    ],
    sections: makeSections(10),
    reviews: makeReviews(),
    updatedAt: "2025-12-05",
  },
  {
    id: "12",
    slug: "nextjs-complete-guide",
    title: "Next.js 15 & React - The Complete Guide",
    subtitle:
      "Learn Next.js App Router, Server Actions, Server Components, and full-stack development",
    thumbnail:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&h=340&fit=crop",
    instructor: instructors[1]!,
    category: categories[0]!,
    price: 15.99,
    originalPrice: 94.99,
    rating: 4.8,
    reviewCount: 19400,
    studentCount: 125000,
    level: "Intermediate",
    language: "English",
    duration: "32 hours",
    lessonCount: 275,
    description:
      "Learn Next.js from the ground up and build production-ready, full-stack ReactJS apps with the App Router!",
    whatYouLearn: [
      "Learn all key Next.js features from the ground up",
      "Build full-stack apps with Next.js App Router",
      "Master Server Components and Server Actions",
      "Build production-ready projects",
    ],
    requirements: [
      "React.js basic knowledge is required",
      "JavaScript and general web dev knowledge is assumed",
    ],
    sections: makeSections(14),
    reviews: makeReviews(),
    updatedAt: "2025-12-18",
    isNew: true,
  },
];

export const enrolledCourses = [
  { ...courses[0]!, progress: 72, lastAccessed: "2025-12-28" },
  { ...courses[6]!, progress: 45, lastAccessed: "2025-12-27" },
  { ...courses[2]!, progress: 18, lastAccessed: "2025-12-20" },
  { ...courses[8]!, progress: 90, lastAccessed: "2025-12-25" },
  { ...courses[10]!, progress: 33, lastAccessed: "2025-12-22" },
] satisfies EnrolledCourse[];

export const wishlistCourses = [
  courses[3]!,
  courses[5]!,
  courses[7]!,
  courses[11]!,
] satisfies Course[];

export const purchases = [
  {
    id: "p1",
    course: courses[0]!,
    date: "2025-11-15",
    amount: 12.99,
    paymentMethod: "Visa •••• 4242",
    status: "completed",
  },
  {
    id: "p2",
    course: courses[6]!,
    date: "2025-10-20",
    amount: 12.99,
    paymentMethod: "Visa •••• 4242",
    status: "completed",
  },
  {
    id: "p3",
    course: courses[2]!,
    date: "2025-09-05",
    amount: 11.99,
    paymentMethod: "Mastercard •••• 5555",
    status: "completed",
  },
  {
    id: "p4",
    course: courses[8]!,
    date: "2025-08-12",
    amount: 14.99,
    paymentMethod: "Visa •••• 4242",
    status: "completed",
  },
  {
    id: "p5",
    course: courses[10]!,
    date: "2025-07-28",
    amount: 13.99,
    paymentMethod: "PayPal",
    status: "refunded",
  },
];
